argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    args:
      statusProcessors: "20"
      operation-processors: "50"
      repo-server-timeout-seconds: "180"
      app-resync: "600"
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
