argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
      - --status-processors
      - "20"
      - --operation-processors
      - "10"
      - --repo-server-timeout-seconds
      - "180"
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
